### ISSUE TITLE
Suport multiple AWB-uri in CreateAwb()

### ISSUE THREAD

**Issue by shusaura85** [firewizard/fancourier-api#5]
Salut,

Se poate adauga suport in **\Fancourier\Request\CreateAwb()** sa se poata crea mai multe Awb-uri in acelasi timp?  
  
Acest lucru ar salva foarte multe request-uri cand sunt create multe awb-uri in acelasi timp.

Cum este implementat in acest moment, ar trebui 2 request-uri pentru fiecare awb creat (unul pentru a genera awb-ul si inca un request pentru a citi html-ul sau pdf-ul awb-ului.  
  
Mersi

**Comment by firewizard** [comment]
Salut,

Interesant ca nu m-a notificat GitHub-ul cand ai deschis tichetul... 

M-am uitat in documentatie, api-ul suporta aceasta functie, ar trebui adaptat codul. Voi analiza ce presupune dpdv cod, iar daca se poate relativ usor, o voi implementa.

Dar ca idee, tot iti vor ramane n+1 requesturi de facut, pentru ca printul (html/pdf) nu merge batch, ci unul cate unul.

**Comment by shusaura85** [comment]
Salut,  

Nu-i problema. Pana la urma am facut o copie a repo-ului si am reusit sa adaug optiunea, si desi crearea de awb-uri in bulk a iesit relativ ok in cod, raspunsul e mai mult hackjob.  
Poti sa vezi aici cum am implementat eu CreateAwbBulk: https://github.com/shusaura85/fancourier-api  

Am adaugat si functiile lipsa pentru refund (e de fapt restitution) - se foloseste de exemplu cand trimiti un colet cu aviz de semnare (si trebuie sa scrii pe awb ca trebuie returnat avizul semnat si stampilat).  

E adevarat ca la descarcare trebuiesc trase individual, dar tot e mai bine sa faci doar 91 requesturi in loc de 180. Asta daca nu dai sa le printezi direct din selfawb (nu e mereu nevoie de html/pdf).

**Comment by firewizard** [comment]
Am implementat si eu functionalitatea, inclusiv restitution-ul (multam de hint). 
Abordarea e putin difrita, dar ideea de baza e cam aceeasi cred.
