### ISSUE TITLE
Mai este de actualitate?

### ISSUE THREAD

**Issue by laurentium85** [firewizard/fancourier-api#6]
Mai este de actualitate api-ul?   Nu am gasit nicio specificare daca foloseste metoda GET sau nu.

_**Începând cu data de 01.04.2022, platforma SelfAWB va renunța la suportul pentru TLS 1.0 și TLS 1.1, trecând la un nivel superior de protecție. De aceea, te rugăm să înștiințezi Administratorul IT al companiei și să te asiguri că, până la această dată, toate sistemele care apelează platforma [www.selfawb.ro](http://www.selfawb.ro/) au activat suportul pentru TLS versiunea 1.2 si toate request-urile pe care server-ul sau aplicația companiei le face către SelfAWB, sunt făcute prin TLS 1.2.**_

Din pacate sunt incepator, si nu imi pot da seama daca mai este de actulitate!

**Comment by firewizard** [comment]
ce anume sa fie de actualitate? modulul functioneaza in continuare fara probleme
