### ISSUE TITLE
Api v2.0

### ISSUE THREAD

**Issue by shusaura85** [firewizard/fancourier-api#7]
Salut,
Ai in plan sa upgradezi codul la API-ul FAN v2? API-ul existent o sa fie retras pe 1 martie 2024.

**Comment by firewizard** [comment]
Salut, 
Cel mai probabil ca voi face upgrade. Nu stiu ce presupune inca, nu am citit documentatia, dar candva la inceput de 2024 ma voi ocupa

**Comment by shusaura85** [comment]
In principiu, au introdus header Authorization cu token generat la login si mai toate functiile returneaza JSON. Nu mai necesita CSV pt trimiterea awb-urilor (o sa fie array multidimensional).  
Documentatia o au publicata aici: https://github.com/FAN-Courier/API-Docs  
Vezi ca arhivele publicate sunt mix de documentatie veche si noul api (il gasesti dupa data modificarii cel mai usor).  
Si ca sa nu pierzi mult timp ca mine, toate requesturile de tip POST accepta doar **application/x-www-form-urlencoded** chiar daca documentatia zice si pare ca accepta JSON (m-a incurat rau de tot asta la crearea de awb).  
Exemplele de la creare awb nu arata campurile necesare pt destinatar pentru persoana de contact, bloc, scara, ap, etaj, astea le gasesti la informatii borderou cum trebuie sa arate. Un alt camp care te poate deruta este "cod", asta e campul de ramburs (vine de la cash on delivery)

Bafta

**Comment by shusaura85** [comment]
Am incarcat versiunea mea pentru API 2.0 aici [shusaura85/fancourier-api](https://github.com/shusaura85/fancourier-api)  
Cred ca o sa te ajute foarte mult pentru implementarea ta (mai ales cand vine vorba de campurile care nu sunt specificate in documentatie).  
`request`-urile si `response`-urile au pastrat in mare parte designul care il ai si tu, dar eu am decis sa adaug si obiecte pentru raspunsuri (unde era cazul) si crearea de awb-uri.
